name: Build QPhotoRec Appimage

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: aarch64
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install \
            build-essential \
            autoconf \
            automake \
            autotools-dev \
            dh-autoreconf \
            git \
            pkg-config \
            libncurses5-dev \
            libncursesw5-dev \
            e2fslibs-dev \
            ntfs-3g-dev \
            libjpeg-dev \
            uuid-dev \
            zlib1g-dev \
            qt6-base-dev \
            qt6-tools-dev \
            libqt6svg6-dev \
            qtbase5-dev \
            qttools5-dev \
            libqt5svg5-dev

      - name: Build Appimage
        run: |
          ARCH=${{ matrix.arch }} bash build.sh

      - name: Upload Appimage
        uses: actions/upload-artifact@v7
        with:
          name: build-${{ matrix.arch }}
          path: "QPhotoRec*.AppImage"

      - name: Release Appimage
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: "QPhotoRec*.AppImage"